package protocol.message;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    SIGNUP_REQUEST,
    SIGNUP_RESPONSE,
    ERROR,
    SEND_MESSAGE_REQUEST,
    INCOMING_MESSAGE,
    DELIVERY_STATUS,

    ONLINE_USERS_REQUEST,
    ONLINE_USERS_RESPONSE,

    SYSTEM_NOTIFICATION,

    DISCONNECT_REQUEST,
    DISCONNECT_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE
}
